# Generated by Django 3.1.7 on 2021-03-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_output_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='edit',
            field=models.IntegerField(default=0),
        ),
    ]
