# Generated by Django 3.1.7 on 2021-03-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20210305_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='sample_id',
            field=models.IntegerField(default=0),
        ),
    ]
