# Generated by Django 3.1.7 on 2021-04-06 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20210322_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Reddit',
        ),
        migrations.RemoveField(
            model_name='output',
            name='edit',
        ),
        migrations.RemoveField(
            model_name='output',
            name='sample_id',
        ),
        migrations.AddField(
            model_name='output',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
